### ISSUE TITLE
Linux desktop app crashes silently at random intervals

### ISSUE THREAD

**Issue by allanlaal** [toggl-open-source/toggldesktop#2019]
first up the app starts up for minutes and when it finally does everythings seems fine, there's a tray icon and everything. Thats probaby because I have thousands of unique time entries it loads into autocomplete history.

after X minutes/hours the app crashes, I usually don't notice it, since I don't use it for time entries, but for tracking running apps.

note that this is certainly not #1977 
I also tested this against #2002 and #1721 by disconnecting/reconnecting 1 and both of my external monitors. Toggl Desktop remained working without issues.

This issue has persisted for more than a year I think.

**Comment by MartinBriza** [comment]
It's a pity this happened 4 years ago because running this in a debugger would be very beneficial for determining where is the crash actually coming from. It's possible it's the autocomplete though, its implementation is not optimal. I'll leave this open for a bit but I'm not sure if we'll be able to fix this particular problem.

**Comment by allanlaal** [comment]
AFAIK this issue persisted up until I stopped using Toggl ~2020-04

I'll close this and if someone else experiences this bug, please comment here!
