### ISSUE TITLE
Add menu option for turning Pomodoro Timer on and off

### ISSUE THREAD

**Issue by twpol** [toggl-open-source/toggldesktop#2094]
As a user who runs Toggl Desktop all day at work and home, I find myself frequently turning the Pomodoro Timer option on and off throughout the day - for meetings at work, playing games and watching TV at home.

I would like a quicker a way to do this than opening Preferences from the notification icon, then having to close the app window afterwards. A toggle menu option (like the mini timer) in the menu would be ideal.

**Comment by oshev** [comment]
I have exactly the same problem. Meetings at work, playing games, and watching TV at home, as you mentioned, are typical cases when I don't need pomodoros. However, when I study or work on my own task, I do need pomodoros.  

Alternative solutions could be 1) a possibility to start tracking with or without a pomodoro (two Play buttons instead of one?), 2) an option to stop pomodoro manually, e.g. via a button in the notification.

A notification when the pomodoro is finished would be useful in any case. I wonder if others also suffer from its absence, but I often miss "pomodoro finished" event because I don't always have the sound on my computer turned on or I listen to a music and I don't notice the "ding!" of pomodoro.

**Comment by IndrekV** [comment]
Thank you for sharing your thoughts. 

`1) a possibility to start tracking with or without a pomodoro (two Play buttons instead of one?)`
This will not happen as it would not fit the design well

`2) an option to stop pomodoro manually, e.g. via a button in the notification.`
There is actually an issue to look into this #2088

The solution would be to add option to the main menu with keyboard shortcut

**Comment by oshev** [comment]
Thank you!

**Comment by retog** [comment]
A way to toggle Toggl Pomodore is indeed a missing feature, there are many ways this could be done, two buttons, checkbox, keyboard shortcut, but having to change the settings really is tedious.

**Comment by ADTC** [comment]
Have you looked at this? #2167

I think a tomato in the title bar is a great way to do a quick on/off of the pomodoro.

**Comment by skel35** [comment]
closing as a duplicate in favor of #2167
