### ISSUE TITLE
Linux App Crashing or Hiding

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#2628]
User is reporting that the Linux app constantly crashes after being open for so long. If it doesn't crash, it occasionally hides in the background and refuses to come out. 

/conversation/19509491733#part_id=comment-19509491733-2300667651

(This conversation includes log files from the app for your reference).

**Comment by MartinBriza** [comment]
In a few reports I closed today I noticed there used to be a problem with the app "hiding in the tray area and refusing to show" which I haven't heard for quite a while at this point, so I consider this problem to be fixed in the recent versions. This is a 2 years old issue though so who knows at this point... :/
