### ISSUE TITLE
Autotracker prompt when project is changed

### ISSUE THREAD

**Issue by bglw** [toggl-open-source/toggldesktop#2656]
I switch between tasks throughout the day, and it would be nice if the autotracker would prompt me to change project when the window title matches a different project than the one currently being tracked.

**Comment by LiptonTipton** [comment]
And only after the window has been in focus longer than a specified time threshold, e.g.5 min.

**Comment by bigelowcc** [comment]
Mm yes that would be nice for the standard tracker anyway. I often get spammed by a few in a row when changing desktops.

**Comment by robsonsobral** [comment]
I'm happy to see this on 7.5.343! Thank you!

May we have a threshold of 10 seconds, the same used on the Timeline feature?

Thank you!

**Comment by skel35** [comment]
Hi @robsonsobral !
Thanks for the feedback, we'll consider adding a threshold shortly.
Would you prefer to have a threshold only for the new scenario (switching projects) or for the previous scenario as well (regular Autotracker notifications when no timer is running)?

**Comment by robsonsobral** [comment]
Hmmnnnn... I haven't thought about it. I'm not sure.

The new scenario is annoying when I already changed project, but still have to close tabs and files from the previous one. I use more than one software all the time. However, the first suggestion has never bothered me. Probably because it happens only one time. I guess, to start is an immediate act, while to change projects isn't.

Am I making sense? 

I'm sorry I can't properly help you.

**Comment by skel35** [comment]
Thanks for explaining your use case. That makes perfect sense.

**Comment by GitMurf** [comment]
I thought I would like this autotracker notification while another timer is going but I actually have found it is super distracting. I have alot of projects that overlap in different ways so basically I am constantly getting this popup every minute or two. Can we add a switch that allows us to turn this off so that we can go back to the old way?

I would also vote that in general we should have a delay (10 seconds would be good) before it recommends anything whether currently tracking time or not (perfect world we could configure this time threshhold).

But for the immediate need, I have turned off autotracker completely just because of how disruptive the new functionality is.

Thanks for all your awesome work though team! Toggl is absolutely a life saver!

**Comment by robsonsobral** [comment]
@GitMurf , hi!

I've the impression you need to exclude the overlapping files from the autotracker filter; so, you can use it without going crazy. The same were happening to me.

**Comment by skel35** [comment]
This has been enabled for Windows in #3976.
The issue about the prompt occurring too often has been moved to #4605.
The issue to enable this for macOS and Linux has been moved to #4606.
