### ISSUE TITLE
Linux distribution version parity

### ISSUE THREAD

**Issue by Spurlos** [toggl-open-source/toggldesktop#3230]
### 💻 Environment

Platform: Linux

### 📒 Description

I have been a long time user of deb distribution of the app. It hasn't been updated in stable channel for a long time, so I have went and checked if same is true for other channels (flatpak, snap). What I have seen is causing questions on such discrepancy in stable versions over different distribution channels
**Latest stable version per channel**
Deb: 122
Flatpak: 356
Snap: 411
![image](https://user-images.githubusercontent.com/667533/63268910-ee966b00-c29d-11e9-9685-64fc6d3c1673.png)

My proposition is to update Linux channels to bring parity in build number, deprecate old channels (deb?) and ask users to use those that are actively supported.

**Comment by MartinBriza** [comment]
Hey,
trust me, we're working on this but every time we're THIS CLOSE to releasing everything at once, we discover a bug that postpones the next stable release for us by a while. We're really close to getting one in the following days/weeks though, so please wait for a bit and hopefully there will finally be version parity. :)
Regarding the current version difference, you're seeing different versions because we've started to add support for flatpak and snap only recently so what you're seeing in those repositories are essentially the first testing versions we've managed to build on these platforms. We, as Toggl, still don't consider them stable nor do we officially endorse using them. However, after we've reached maturity with those packages, we're hopefully going to deprecate at least the deb package. 
If you're interested in testing newer versions of official packages, you can watch this page: https://toggl.github.io/toggldesktop/installers/ . We're advertising the latest stable, beta and dev versions for each platform (while I don't really understand why deb64 beta is not there at this moment but we'll fix that, too).
Please feel free to report more bugs or ask further questions ;)

**Comment by Spurlos** [comment]
Thanks for a fast reply. I'm looking forward to test something semi stable on any proposed channel. Snap/flatpack looks looks promising, but I think I would need to stick to Deb for now.

**Comment by MartinBriza** [comment]
Ok, I think it is safe to close now. We're now able to release everything at the same time.
As for flatpak/snap, we're currently doing only Flatpaks (there is a Snap package but it's unpublished because we're hitting issues with it all the time and it causes bad rating in the GNOME app store for us). You can get the Flatpak version here: https://flathub.org/apps/details/com.toggl.TogglDesktop
