### ISSUE TITLE
dbus-launch: command not found when running toggldesktop installed with snap

### ISSUE THREAD

**Issue by Fensterbank** [toggl-open-source/toggldesktop#3357]
I installed toggldesktop via snap. One time with Gnome Software Manager, the other time by command `sudo snap install --edge toggldesktop`.

I cannot start the tool because of an error message.

### 💻 Environment
Fresh installation of Ubuntu 19.04 Budgie-Edition.

Platform: Linux
OS Version: Ubuntu Budgie 19.04
Toggl Version: 7.4.991

### 🐞 Actual behavior
```
$ toggldesktop 
/snap/toggldesktop/6/bin/TogglDesktop.sh: line 24: dbus-launch: command not found
```

### 💯 Expected behavior
The app should start.

### 🔨 Steps to reproduce
1. Install Ubuntu Budgie 19.04
2. Install Toggl Desktop by using the Gnome Software installer
3. Try to start the app

**Comment by MartinBriza** [comment]
While I don't understand why `dbus-launch` is not present in your system, I'll look into it. It's also possible there are some distros running absolutely without D-Bus and I don't see a reason why TogglDesktop shouldn't run there.

**Comment by Fensterbank** [comment]
Thanks for your fast reply.

> While I don't understand why `dbus-launch` is not present in your system

The weird thing is: dbus is installed and dbus-launch is present.
```
$ which dbus-launch
/usr/bin/dbus-launch
```
I have no idea, how snap packages are working... I thought it may have something to do with these containerization things.

> It's also possible there are some distros running absolutely without D-Bus and I don't see a reason why TogglDesktop shouldn't run there.  

For clarification: Ubuntu Bugdie is a community flavor of Ubuntu (an official Ubuntu with another preconfigured desktop environment), so under the hood it's the same as Ubuntu.

I have to mention since the tarball beta is working great for me now (as discussed in the other thread), I won't personally care about this snap issue anymore. :)

**Comment by MartinBriza** [comment]
Yeah, it's possible it's caused by the sandboxing of Snap apps. To be honest, I really don't know why `dbus-launch` is in the script. We can probably get rid of it, or at least add a failsafe branch for when it's not present. I've never really looked into it though because it simply didn't occur to me that it's possible to NOT have it on a GUI-enabled system. Seems with snaps it is.

I'm glad tarball works right for you! 

But I'm also really glad you opened this issue - dealing with bugs in our Snap and Flatpak packages is of great importance at this moment for us, because we'd like to have as many users using those instead of tarballs and debs because it's much easier to deal with the dependencies that way.
