### ISSUE TITLE
UNIQUE constraint failed error

### ISSUE THREAD

**Issue by jrsacher** [toggl-open-source/toggldesktop#3374]
### 💻 Environment

Platform: macOS

OS Version: macOS 10.14.6

Toggl Version: 7.4.1012, 7.4.484

### 🐞 Actual behavior

Error message: "Constraint violation: UNIQUE constraint failed: time_entries.uid, time_entries.id"

The application then (usually) hangs and has to be force-quit.

I've also seen the same error message as issue #3372 -- no idea if there's a relation.

### 💯 Expected behavior

No error messages, syncing between desktop, phone, and web

### 🔨 Steps to reproduce

1. Open Toggl Desktop
2. Start tracking time
3. See errors

Note: I often start an entry on my phone and stop it on desktop (or vice versa). Don't know if this contributes. Entries seem to be working via the Android app and web.

### 📦 Additional info

Have tried both clearing the cache and reinstalling the desktop app. It downloaded 7.4.484, and the error showed up there as well. The "restart app to upgrade" button isn't working now, either.

This was submitted via the feedback option in the Help menu, but wanted to create an official report here.

![Screen Shot 2019-09-30 at 9 31 24 AM](https://user-images.githubusercontent.com/31259475/65885291-6315fc80-e368-11e9-8553-81283cd4c49a.png)

**Comment by hadri3n** [comment]
I have **macOS 10.14.6** and have the exact same issue.
I do not use the Mobile App however. Only the web and desktop app.

I started seeing that message today.

**Comment by NickG-WC** [comment]
The same situation, this has occurred for me in the last few hours.  It is also affecting the Windows 10 users on my team.

I've just had to start using the web interface as that works ok.  If I reopen the Desktop App it stops the timer I had running and restarts the last timer open in the desktop app.

**Comment by IndrekV** [comment]
We're working on this and try to get is solved as fast as possible. Thank you for escalating this issue.

**Comment by skel35** [comment]
> After looking into bugsnag I see `CONSTRAINT` errors appeared first in release `7.4.422`

I can see these errors in `7.4.345`, `7.4.330` and other older versions. [Breakdown by version](https://app.bugsnag.com/toggldesktop/toggldesktop/timeline?filters[event.since][0][type]=eq&filters[event.since][0][value]=all&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=constraint&filters[search][1][type]=eq&filters[search][1][value]=violation&sort=last_seen&pivot_tab=release.seen_in). We only have error data 2 months back that's why older clients are rare so we can't reliably tell where the errors appeared using Bugsnag.

**Comment by IndrekV** [comment]
This seems correct. I think I looked at some other specific error and it didn't show it for other versions. 7.4.330 seems to be the first version bugsnag has detected.

**Comment by tumb1er** [comment]
Is there any workaround? Clear cache does not work
