### ISSUE TITLE
Reduce numerous workspace/preferences fetches

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3417]
### 💻 Environment
Platform: Library

### 📒 Description
We fetch `/workspaces/preferences` too many times. It is actually used to detect if the user has any workspaces left. Currently, it seems that it is triggered every time the user gets an error from the backend. We should narrow it down to certain error that indicates this scenario is possible. The error is probably something like `403 Forbidden`

**Comment by skel35** [comment]
### Problem
Every time the periodic or manual syncing is done, we're performing 4 requests to the server: `/me`, `/me/workspaces`, `/me/workspaces/preferences`, and `/me/preferences/desktop`.

### Proposed solution
- Do not perform  `/me/workspaces/preferences/` and `/me/preferences/desktop` requests when _periodic_ syncing is done.
- Keep performing all 4 requests when full syncing is done.
- When the client receives an error due to locked time entry, perform `me/workspaces/preferences` request in order to update the information on locked reports in the workspaces that could cause the locked time entry error.

This reduces the number of requests during non-user-triggered syncs by 50%.

**Comment by skel35** [comment]
@IndrekV In order to test the solution in the case when the entries are locked during the application runtime, I'd need access to or the help of an admin account of a premium workspace. Could you please help with that?
