### ISSUE TITLE
End time field being reset to  previous value

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#3472]
### 💻 Environment

Platform:  MacOS
OS Version:  10.14 
Toggl Version:  7.4.1023

### 🐞 Actual behavior
While filling out a time entry, the end time field gets reset to previous value while you are entering it. 

### 💯 Expected behavior
The time entry field should accept and store input and not change it. 
### 🔨 Steps to reproduce
[Video](https://toggl.slack.com/files/UHVETTGTW/FPSNW1K08/toggl_end_time_disappears.mp4)

### 📦 Additional info
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24256231973)

**Comment by NghiaTranUIT** [comment]
User mentions two issues
1. AutoComplete View appears, hide the TimeEntry List unexpectedly there is no way to close it. (Video toggl_where_are_my_time_entries.mp4 in their conversation)
It would be fixed in https://github.com/toggl-open-source/toggldesktop/pull/3507

2. Change the start date cause the end date updated too.
I'm investigating on it 👍

**Comment by NghiaTranUIT** [comment]
@IndrekV The user complains that when 
- He changes the start time, the end time would be updated too.
- Sometime the TimeEntry moves to previous day.

I investigated and it turns out that it's our intention from the library.

https://github.com/toggl-open-source/toggldesktop/blob/0089dab2718ddcef19472e0f01a7a63ce9bcc1d3/src/time_entry.cc#L308

https://github.com/toggl-open-source/toggldesktop/blob/0089dab2718ddcef19472e0f01a7a63ce9bcc1d3/src/context.cc#L3212-L3217

From my experience during using Toggl, I often encounter two above issues and it's confused me.

What should we do?
