### ISSUE TITLE
https://github.com/toggl-open-source/toggldesktop/releases/latest leads to confusing place 

### ISSUE THREAD

**Issue by tjluoma** [toggl-open-source/toggldesktop#3517]
### 📒 Description

<https://github.com/toggl-open-source/toggldesktop/releases/latest> should automatically redirect to the latest non-beta release.

Instead it redirects to <https://github.com/toggl-open-source/toggldesktop/releases/tag/v7.636>

Now, since <https://toggl.github.io/toggldesktop/> says that the latest version is '7.4.1041' it would _seem_ logical that 7.636 is a _later_ release, but if you go to <https://github.com/toggl-open-source/toggldesktop/releases/tag/v7.636> it says "tanel released this on Apr 25, 2014".

Since the current date is Nov 15, 2019, this is *very confusing.*

**Comment by IndrekV** [comment]
Thank you for elevating this issue. We have not used the github releases as it is meant to be used because we always have 3 different releases (windows, linux and mac). They are released at separate times and have separate version numbers. This means that there is never a correct latest release that features all the platforms together. 

Never the less the latest links should not point to an ancient version.

**Comment by IndrekV** [comment]
I've removed the reference of latest release to an ancient version and that's all we can do about it now. Please check the links in readme for the latest stable release packages.

Thank you again for your feedback.
