### ISSUE TITLE
How to build on Windows 10 with Visual Studio 2019?

### ISSUE THREAD

**Issue by sterid** [toggl-open-source/toggldesktop#3544]
### 💻 Environment

Platform: Windows 10 1903
Visual Studio: VS 2019 with `.NET desktop development`, `Desktop development with C++` and `Universal Windows Platform development`

### 📒 Description

Hi everyone. 
I want to modify some behavior of pomodoro notification. But I'm not really good with VS and Qt. So I installed VS with 3 dependencies as described in _readme.md_ and tried to open project in VS. I got an error: 
> CMake Error at C:\GIT\toggldesktop\CMakeLists.txt:42 (find_package):
>  Could not find a package configuration file provided by "Qt5Widgets" with any of the following names:
>
>    Qt5WidgetsConfig.cmake
>    qt5widgets-config.cmake
>
>  Add the installation prefix of "Qt5Widgets" to CMAKE_PREFIX_PATH or set "Qt5Widgets_DIR" to a directory containing one of the above files.  If "Qt5Widgets" provides a separate development package or SDK, be sure it has been installed.	TogglDesktop	C:\GIT\toggldesktop\CMakeLists.txt	42		

I didn't install QT at this moment, should I? Which option must be intalled for VS2019? 
<img src=https://dl.dropboxusercontent.com/s/5z9gypqbxi9et4y/2019-11-21_10-15-39.jpg>

I already tried to search info about building on github:
* [3057](https://github.com/toggl-open-source/toggldesktop/pull/3057) and [2852](https://github.com/toggl-open-source/toggldesktop/issues/2852) didn't clarify how to run
* [Wiki urls](https://github.com/toggl-open-source/toggldesktop/wiki) don't work anymore (redirect to readme.md)

How to build toggle desktop?

**Comment by skel35** [comment]
Hi @sterid !
Qt and Cmake instructions do not apply for Windows.
Windows app can be built simply by opening the `src\ui\windows\TogglDesktop\TogglDesktop.sln` in Visual Studio, switching to `Debug` configuration and pressing F5 (First build might take up to 10 mins because C++ prerequisite libraries have to be built). The windows app is a WPF app so Qt is not used.
Please let me know if that works for you and thanks for the feedback, we'll try to make `readme` less confusing.

**Comment by sterid** [comment]
@skel35 thanks. it works like a charm now :)
