### ISSUE TITLE
Idle notification window not in foreground

### ISSUE THREAD

**Issue by sojusnik** [toggl-open-source/toggldesktop#3602]
After the new update, the idle notification window is not in the foreground any more. Instead, you have to click the system notification popup and only after that it will come to the foreground, where you can choose what to do with idle time. This is a step backwards compared to the previous version, because you have to click more.

Additionally, the system notification popup shows double brackets around the idle minutes.

Platform: Linux
OS Version: Ubuntu 19.04
Toggl Version: 7.4.528

**Comment by sojusnik** [comment]
Also the idle notification window won't be opened after clicking on the system notification popup, when Toggl was previously minimized.

**Comment by MartinBriza** [comment]
We had reports about the notifications being too intrusive. However, for the idle notification this shouldn't matter because the user was very likely to be gone before the notification pops up. I'll work on changing this but probably not right for the next version.
I'm now working on redesigning the app so it's pretty likely this will get changed with the redesigned version.

**Comment by sojusnik** [comment]
> I'm now working on redesigning the app so it's pretty likely this will get changed with the redesigned version.

Sounds great! Any ETA?

**Comment by MartinBriza** [comment]
Referencing #3629

**Comment by MartinBriza** [comment]
This is probably fixed by forcing the window to raise. Please feel free to reopen if it still doesn't work as expected for you. Thank you.
