### ISSUE TITLE
Editing the start time of an existing entry will automatically edit the end time as well

### ISSUE THREAD

**Issue by VeljkoTN** [toggl-open-source/toggldesktop#3639]
### 💻 Environment

Platform: Windows
OS Version: Windows 10
Toggl Version: 7.4.1092

### 🐞 Actual behavior
Editing the start time of an existing time entry will edit it's end time as well - it basically tries to keep the original duration and a user would like to simply edit the start time when they stop the timer after starting the timer late. 

### 💯 Expected behavior
Editing the start time should edit the start time and the duration but not the end time

### 🔨 Steps to reproduce

1. Create a time entry or use an existing one (not a running timer).
2. Click on it to access the edit view
3. Change the start time and see how the end time changes for the exact same time to keep the original duration. 

### 📦 Additional info
![Editing start time desktop](https://user-images.githubusercontent.com/36152180/71097857-0381fd00-21b1-11ea-83f2-a2a6cf217bc9.gif)

**Comment by NghiaTranUIT** [comment]
It's our intention to update the End Time and keep the Duration. We can disable it by enabling the "Change duration when changing Start Time" in Preference.

<img width="520" alt="Screen_Shot_2019-12-24_at_13_47_47" src="https://user-images.githubusercontent.com/5878421/71398756-0f0f7100-2654-11ea-91a4-4cef83ba7978.png">

On the other hand, we decided to enable this option by default (https://github.com/toggl-open-source/toggldesktop/pull/3647) since it's natural action from the users
