### ISSUE TITLE
Details popover hides behind other always on top windows

### ISSUE THREAD

**Issue by mdmagahis** [toggl-open-source/toggldesktop#3646]
### 💻 Environment

Platform: macOS
OS Version: macOS 10.14.6
Toggl Version: 7.4.1092

### 🐞 Actual behavior
NSPopoverWindow containing Details, Duration, etc. hides behind "always on top" (AOT) windows (i.e. iTunes MiniPlayer) when TogglDesktop window is at or beyond/behind the AOT window.

### 💯 Expected behavior
A possible solution might be to have the popover open within the TogglDesktop window instead of to the side; similar to behavior when ToggleDesktop window is maximized or fullscreen.

This is obviously an edge case, but it took me a while to understand why the pop over wasn't showing up. 

### 🔨 Steps to reproduce

1. With the TogglDesktop window at a screen's edge, align or position TogglDesktop standard window side-by-side with or extending behind a window that is deemed "always on top" or "floating" (i.e. iTunes MiniPlayer and Picture-in-Picture video). 
2. Open the editing pop over either by clicking a Time entry cell or pressing the `Return` key
3. The expected pop over opens, just behind the floating/AOT window.
4. Verified in other applications that use NSPopoverWindow (Calendar.app, Messages.app)

* _Issue occurs on right and left side of TogglDesktop window where AOT window is on the opposite edge of the TogglDesktop's window edge touching the screen's edge_

### 📦 Additional info
<img width="1440" alt="Screen Shot 2019-12-19 at 10 56 18 AM" src="https://user-images.githubusercontent.com/20567044/71193519-ddf80080-224f-11ea-8084-bf1488fff6f9.png">

It seems this is also the case with other NSPopoverWindows that display outside of the application's window; verified in native macOS Calendar.app.

**Comment by NghiaTranUIT** [comment]
Thank for detailed report. I will look on it in this milestone 👍

**Comment by NghiaTranUIT** [comment]
Hey there, here is what I investigated:

1. The editor popover would be behind the Windows (iTune MiniPlayer or Picture-in-picture), which is Always On Top / Floating mode as you described 
=> It's correct behavior because this AOT is the most top of window and there is no way to make the Editor above.

2. You can workaround by enable "Keep Toggl on top of other windows" in Preference
<img width="661" alt="Screen_Shot_2019-12-20_at_14_33_26" src="https://user-images.githubusercontent.com/5878421/71238108-dd399a00-2335-11ea-854c-4d8203b98a26.png">

The result is what you're looking for

![Screen Shot 2019-12-20 at 14 30 07](https://user-images.githubusercontent.com/5878421/71238122-e4f93e80-2335-11ea-8a15-d69156b34e29.png)
