### ISSUE TITLE
Time entry pill resizing for Timeline view

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3711]
### 💻 Environment
Platform: macOS

### 📒 Description

Designs are in Zeplin

The logic:

- Cursor changes to resize cursor on the top and bottom edge of the time entry pill
- When user starts to drag a tooltip is shown on the right that displays the `start time - end time` and `duration` so it's easy to see the exact effects of resizing
- The info component right to the pill should act as in regular view. So when pill item is resized to smaller size some info will be hidden
- Resizing a pill should not affect other time entries. If user resizes on top of another timen entry then there will be an overlap and user has to fix it if they want.
- Resizing will snap in certain minutes. With closes zoom 5minute increments with all other zoom levels 15 minute increments. (this is up for discussion. Not sure this is needed, maybe 15 minutes for all places.)
- All items are resizable. Even the items that are not in the first column

**Comment by NghiaTranUIT** [comment]
> Resizing a pill should not affect other time entries. If user resizes on top of another time entry then there will be an overlap and user has to fix it if they want.

From the design, the resize action on selected TE actually affects on the next TimeEntry (Yellow) (but not the second next (Red)).
 
<img width="1039" alt="Screen_Shot_2020-01-10_at_17_56_05" src="https://user-images.githubusercontent.com/5878421/72148245-e963c500-33d2-11ea-996b-af24d1a1704f.png">

**Comment by IndrekV** [comment]
This part had not been 100% confirmed. I commented this logic to the designers and have not heard back from them. I don't agree with the design on this point.

My vision would be to not edit other entries when resizing. The reason being that this would not work if user wants to drag on entry to be longer than the next two. This scenario would create a lot of confusion. 
Would it only resize the next entry and then block movement? 
Would it resize all next items?

**Comment by NghiaTranUIT** [comment]
For the sake of simplicity and the discussion in Slack, I would choose the first approach, which is:
- The current resized Timeline Entry **doesn't** affect on other entries.

**Comment by NghiaTranUIT** [comment]
![Screen_Shot_2020-01-22_at_14_21_42](https://user-images.githubusercontent.com/5878421/72873667-ef3a9e00-3d22-11ea-99da-b4c6b168b3ab.png)

From the design, we could split the Timeline TimeEntry pill into three parts:
1. The Top area: Resize Cursor => Able to drag to resize
2. Middle area: Pointing hand Cursor => Able to click to present the Editor
3. Bottom area: Resize Cursor => Able to drag to resize.

It works well with those TEs, which has reasonable width, but it's not for the Tiny TimeEntry

## Question: How do we handle the Resize, Hover and Click action on the Tiny TimeEntry?
### Possible Answer 1:
- Disable Resize Area
- Keep the Hover and Click action

### Possible Answer 2:
- Disable Hover action
- Enable Resize action in *entire* pill -> Easy to resize, but impossible to click

### Possible Answer 3:
- Keep all actions
=> Hard to interact because the area for resize is so tiny and it easily messes up with the Hover action.

**Comment by IndrekV** [comment]
As a reference the decision also here:

> is it possible to have the resize and click events working at the same time or they block each other. When you click and don’t drag it’s a click and when you drag it’s resizing?
If they block each other I would say to disable resize for small items. If the user needs to resize they either edit the item or change zoom and resize when the pill is bigger.

We'll go with **Solution no.1** for small pills

**Comment by NghiaTranUIT** [comment]
Unfortunately, [UISnapBehavior](https://developer.apple.com/documentation/uikit/uisnapbehavior) isn't supported on macOS. It's what we're looking for, to implement the Snap Behavior when resizing. 

It seems that we have to manually implement it for the "Snap feautre"
