### ISSUE TITLE
Review request encoding logic

### ISSUE THREAD

**Issue by IndrekV** [toggl-open-source/toggldesktop#3780]
### 💻 Environment
Platform: Lib

### 📒 Description
In `https_client.cc` line 411 we have
```
        poco_req.set("Accept-Encoding", "gzip");
```
This is set after the request has been executed. We need to check if we need to add it to the actual request and what are the limitations

**Comment by NghiaTranUIT** [comment]
It's definitely a bug. Here is a result:

### Testing Scenario 
1. Open Proxyman or Charles Proxy
2. Open Toggl Desktop on master (Don't use Production build, since TogglDesktop supports SSL-Pinning, which prevent Man-in-the-middle app intercepts the request and response)
3. Play around and check whether or not the Response is compressed and has `Content-Encoding` header.

### Current production build
- No compressed response
- No `Content-encoding` header

<img width="2032" alt="Screen_Shot_2020-02-11_at_16_01_28" src="https://user-images.githubusercontent.com/5878421/74222947-2da2f780-4ce8-11ea-8c8f-197aed8a4c2f.png">

**Comment by NghiaTranUIT** [comment]
The PR is at https://github.com/toggl-open-source/toggldesktop/pull/3801
