### ISSUE TITLE
Crash when editing mini timer current project and not logged in

### ISSUE THREAD

**Issue by Bernier154** [toggl-open-source/toggldesktop#3937]
### 💻 Environment
Platform: Windows/Linux
OS Version: 10 Family v18363.720
Toggl Version: 7.6.46 64bit

### 🐞 Actual behavior
My toggl config open on mini timer by default, and the app is minimized in the right bar. If i don't check if i'm logged in and edit the field in the mini timer, toggl crashes.

### 💯 Expected behavior
Toggl app could be greyed out if not logged in. 
Login form from the app should appear if not logged in.

### 🔨 Steps to reproduce
1. set up toggl as mini timer
2. log out if not currently logged out (when I started th app i was already logged out without knowing)
3. edit the "what are tou doing entry", maybe add some project but i don't think it would change anything.

### 📦 Additional info
I don't see a keep me logged in option, but that is an additionnal thing.

**Comment by skel35** [comment]
Hi @Bernier154, thanks for the report!
We have fixed the crashing issue by hiding the mini timer as soon as the user is logged out.
The fix is available in the current [beta version](https://toggl.github.io/toggldesktop/download/windows64-beta/) (7.5.92+) together with the updated design.

Regarding the logging out issue - our app isn't supposed to log the user out in normal circumstances unless the user explicitly logs out, clears the cache, or resets the API token.
If you keep encountering the app logging you out, please reach out to support@toggl.com or open another issue with steps to reproduce and we will definitely look into it.
