### ISSUE TITLE
App Crashes When Opening

### ISSUE THREAD

**Issue by TheSoloJake** [toggl-open-source/toggldesktop#3938]
### 💻 Environment

Platform: Windows
OS Version: Windows 10 Pro (64-bit) 
Toggl Version: 7.5.46 (stable)

### 🐞 Actual behavior
As soon as the app is opened, it crashes. Plain and simple. "App opens, I see the app in the notification bar, then it closes". 

### 📦 Additional info
User [report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26334350842)

**Comment by skel35** [comment]
[Bugsnag link](https://app.bugsnag.com/toggldesktop/toggldesktop/timeline?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[search][0][type]=eq&filters[search][0][value]=is&filters[search][1][type]=eq&filters[search][1][value]=not&filters[search][2][type]=eq&filters[search][2][value]=a&filters[search][3][type]=eq&filters[search][3][value]=valid&filters[search][4][type]=eq&filters[search][4][value]=value&filters[search][5][type]=eq&filters[search][5][value]=for&filters[search][6][type]=eq&filters[search][6][value]=property&filters[search][7][type]=eq&filters[search][7][value]=%27Width%27&pivot_tab=user.id)
Error: System.ArgumentException: '-9,22337203685478E+18' is not a valid value for property 'Width'.

**Comment by skel35** [comment]
@TheSoloJake the user cannot find the database file because Microsoft Store installation is using a database file from a different location. It's in the `%LOCALAPPDATA%/Packages/`, directory name starting with `TogglO.TogglDesktop`, then `LocalCache/Local/TogglDesktop` (e.g. `%LOCALAPPDATA%/Packages/TogglO.TogglDesktop_txsjqv20xc8gw/LocalCache/Local/TogglDesktop`).

Deleting the database file will help resolve the issue for the user until we fix the bug.
