### ISSUE TITLE
Newest builds on linux

### ISSUE THREAD

**Issue by furai** [toggl-open-source/toggldesktop#4087]
### 💻 Environment
Platform: Linux

### 📒 Description
Hey,

Is there any advantage to install latest linux version over [the only one mentioned here](https://toggl.github.io/toggldesktop/#linux) as having any changes to linux platform.

Current toggle version is `7.5.146` but the site says that `7.4.1111` is the last for linux to have any changes to it.

Did nothing really change for linux since then? No underlying libraries?

Cheers,
Furai

**Comment by furai** [comment]
Can anyone answer my question? Thanks in advance!

**Comment by skel35** [comment]
Hi @furai!
The latest `stable` Linux release was `7.4.528` and `beta` was `7.4.1111`. The list of beta and stable releases is displayed [here](https://toggl.github.io/toggldesktop/#linux).
We have newer builds built automatically from `master` which can be found [here](https://github.com/toggl-open-source/toggldesktop/releases), but those weren't tested and we can't guarantee they're working properly.
We're planning to get back to the Linux app very soon, so we'll test, fix bugs, and publish a new stable Linux release soon-ish. Stay tuned!

**Comment by furai** [comment]
I'm usually installing newest deb available straight from releases and so far I haven't found any outstanding issues. Right now I'm using 7.5.2xx on linux and it works fine but I just assumed that nothing really changed code-wise since last "beta" release. Am I wrong with that assumption?

**Comment by MartinBriza** [comment]
Yeah you're mostly right on that. The fact is I was occupied with other duties and I couldn't fully dedicate to pushing a new stable release out. There is (hopefully) not much of a noticeable difference in current releases to 7.4.528, except for a lot of internal changes in the underlying library.
I'm going through the app at this moment and checking if one of the already released versions is okay to be pushed out as a new beta (hopefully becoming the next stable version). If not, we'll have to wait for a few weeks because there's a lot of possibly breaking changes in the underlying code in current master.

**Comment by MartinBriza** [comment]
Soo, we're able to get Linux releases out pretty often now so I'm closing this.
