### ISSUE TITLE
Add Unit Test Target to macOS Project

### ISSUE THREAD

**Issue by NghiaTranUIT** [toggl-open-source/toggldesktop#4107]
### 📒 Description
It's time to add a Unit Test Target to macOS Project

### 💻 Environment
Platform: macOS

### ⭐️ Acceptance Criteria
- [ ] Add Unit Test Target on TogglDesktop (mac)
- [ ] Add some basic test cases for testing
- [ ] Make sure the test target is able to build and run
- [ ] Add a flow to Github Action to trigger the Unit Test

**Comment by AndrewVebster** [comment]
The issue was closed but two items were not completed:

- Add some basic test cases for testing
- Add a flow to Github Action to trigger the Unit Test

Adding this to GitHub Actions will be useless unless we have some tests to run. So I think we can postpone this.

@skel35 @NghiaTranUIT should I create a separate issue?

**Comment by skel35** [comment]
Yes, let's have a separate issue for those items
