### ISSUE TITLE
Stick mini timer to the top

### ISSUE THREAD

**Issue by atlanteh** [toggl-open-source/toggldesktop#4160]
### 💻 Environment
Platform: Windows
OS Version: Windows 10.1
Toggl Version: 7.5.162

### 🐞 Actual behavior
Trying to stick the mini-timer to the top of the screen is not possible. The timer keeps jumping few pixels down and it leaves a gap at the top

### 💯 Expected behavior
The mini-timer sticks to the top with no gap

### 🔨 Steps to reproduce

1. Show mini-timer
2. Drag the mini-timer to the top of the screen

### 📦 Additional info

![image](https://user-images.githubusercontent.com/3952700/84238263-75555680-ab03-11ea-9629-4e3698267e0e.png)

**Comment by skel35** [comment]
Thanks for reporting the issue @atlanteh !

This has already been fixed. Currently, the fix is available in the `dev` channel, but will soon be available in `beta` and `stable` channels as well.
You can find the channel switcher by clicking cogwheel->About.

Thanks for using Toggl and have a nice day!
