### ISSUE TITLE
Linux app crashes on network disconnection 

### ISSUE THREAD

**Issue by nidarasheed** [toggl-open-source/toggldesktop#4253]
### 💻 Environment

Platform: 
OS Version: 
Toggl Version: 

### 🐞 Actual behavior

Linux app crashes when user is running in a task (timer started) and the network disconnects.
![image](https://user-images.githubusercontent.com/49634673/87923810-7204a180-ca97-11ea-8c5c-aa669aa0a43b.png)

### 💯 Expected behavior
App should not crash

### 📦 Additional info

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300030915)

**Comment by MartinBriza** [comment]
Soo, while I still haven't been able to fix this, I'm able to reproduce the behavior, the steps are:
 * Be on a working network with correctly configured DNS
 * Run TogglDesktop
 * Switch to a network with busted DNS (I do this by changing my network configuration to only have `localhost` as DNS server but keep DHCP-assigned IP, then reconnect to the same network)
 * Sync
 * The app should now show the DNS error from the screenshot above

HOWEVER, that error from the screenshot is probably not the cause of this issue. According to my debugging, the issue seems to be coming from a `QNetworkRequest` use. The only place we're using those is in the `bugsnag-qt` internal library. I'm now trying to fix it but I don't really seem to be able to determine why is it actually happening.
