### ISSUE TITLE
Latest deb (v7.5.247) isn't installing correctly

### ISSUE THREAD

**Issue by furai** [toggl-open-source/toggldesktop#4332]
### 💻 Environment
Platform: Linux

### 📒 Description
I haven't dug deeper but when installing toggl via latest deb (v7.5.247) the desktop entry and binaries in path are gone. 
No idea when it stopped working but v7.5.226 seems to be working correctly.

**Comment by MartinBriza** [comment]
The deb package should actually be okay now (or better than before, at least).
From looking at the package, it installs the following files:
```
/usr/bin/TogglDesktop.sh
/usr/share/applications/com.toggl.TogglDesktop.desktop
```
Which should be enough to put TogglDesktop in your DE menu.
The rest of files (except for metadata) is now put into `/usr/lib/toggldesktop` to not pollute the rest of the filesystem which seems to be the right way to do this (while I may not be doing it 100% correctly though).
Since the desktop filename has probably changed in the meantime, is it possible it's necessary to restart your DE first to actually see the entry in your applications menu?
If that doesn't help, can you please specify the OS version and DE you're using?

**Comment by furai** [comment]
I'll try finding some time for it next week. Right now I need a working application. :)

**Comment by MartinBriza** [comment]
7.5.247 works though! If it's not in the menu (and it is, for me at least), then there's the `TogglDesktop.sh` binary in `PATH`.
Anyway, I'll be waiting for your input, thanks :)

**Comment by furai** [comment]
So apparently the only thing that is not working is the desktop file. I can see `TogglDesktop.sh` in my path, I can launch it without problems from terminal. 

From the freedesktop documentation:
| Key | Description |
| --- | --- |
| TryExec |  Path to an executable file on disk used to determine if the program is actually installed. If the path is not an absolute path, the file is looked up in the $PATH environment variable. If the file is not present or if it is not executable, the entry may be ignored (not be used in menus, for example).  |

So I've edited the entry from `TryExec=TogglDesktop` to `TryExec=TogglDesktop.sh` and now it shows up and works.

Another option would be to symlink upon installation TogglDesktop to TogglDesktop.sh

**Comment by furai** [comment]
Thanks.

**Comment by MartinBriza** [comment]
Thank you for the report and sorry for taking so long to fix this! Let us know if there's anything else we can fix.

**Comment by furai** [comment]
Just verified that this fix works.
