### ISSUE TITLE
Add Activity and TEs visualization [Timeline UI]

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4370]
### 💻 Environment

Platform: Windows

### 📒 Description
This is a sub-task of #4269 .

- Implement displaying activity blocks and popup with info on each activity block hover.
- Add basic Time Entry pills visualization with an algorithm for laying them out when TEs overlap
- Add create TE from gaps functionality.

**Comment by atsvirchkova** [comment]
I cannot understand/find how to calculate activity blocks heights and colors. Looking at MacOS app didn't help, I still don't see the logic 😞

**Comment by skel35** [comment]
The activity pill color calculation is in the `TimelineActivity.swift`:
https://github.com/toggl-open-source/toggldesktop/blob/ba9eb3c686d7ab77e3ed794a68d74ef05b0ceb05/src/ui/osx/TogglDesktop/Features/Timeline/Models/TimelineActivity.swift#L63
https://github.com/toggl-open-source/toggldesktop/blob/ba9eb3c686d7ab77e3ed794a68d74ef05b0ceb05/src/ui/osx/TogglDesktop/Features/Timeline/Models/TimelineActivity.swift#L83-L87

Just pick the lightest possible color, the darkest possible color, and mix between them so that 15 min duration corresponds to the darkest possible color, and 0 mins - the lightest. The lightest color is defined as a semi-transparent color.
The colors used to be blue, but with the new rebranding we should go with the purple.
You can just use `Toggl.AccentColor` as the darkest one, and `Toggl.AccentColor` with 20% opacity as the lightest one.

**Comment by skel35** [comment]
it looks like now the resulting color always has the alpha layer = 1.0, so it doesn't even change depending on the duration.
you can use the static color for now as well, we can introduce the changing color later on both macOS and Windows.

**Comment by atsvirchkova** [comment]
Thank you. And what about the height? Should it somehow depend on Activity chunk events total duration?

**Comment by skel35** [comment]
Yes, the height is directly proportional to the total duration of the events in the chunk
