### ISSUE TITLE
Duration field sometimes retains previous time entries duration

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl-open-source/toggldesktop#4411]
### 💻 Environment

Platform:MacOS
OS Version: 10.15.6
Toggl Version:  osx_native_app/7.5.260

### 🐞 Actual behavior
The desktop app is sometimes retaining the duration of the previous time entry even when there's currently no entry running.

### 💯 Expected behavior
Duration field to clear.

### 🔨 Steps to reproduce
I haven't actually been able to replicate this yet but I haven't been able to stop this for happening for the user either. Is it possible that this is related to something being blocked by a firewall?

### 📦 Additional info
There's a screenshot in the [case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2144650/conversations/106481303549509)

**Comment by ioveracker** [comment]
This appears to be fixed in 7.5.268.

Steps to reproduce:

1. Ensure that “Stop running entry on computer sleep/shutdown” is enabled in Preferences. 
2. Start a timer. 
3. Put your computer to sleep. 
4. Wake your computer. 
5. Observe that your last entry has been saved as expected, but the current time entry fields have not been cleared. You must manually clear them, otherwise pressing the start button to start the timer will resume at the last time, creating an entry that overlaps with the previous entry.

**Comment by skel35** [comment]
this is correct, fixed in 7.5.268
