### ISSUE TITLE
Possible NullReference exception when referencing AlphaFeatures

### ISSUE THREAD

**Issue by atsvirchkova** [toggl-open-source/toggldesktop#4425]
### 💻 Environment

Platform: macOS,Windows,Linux
Toggl Version: 7.5.275

### 🐞 Actual behavior
A user reports consistent crashing of his desktop app after 2-3 minutes of use.

### 💯 Expected behavior
No crash.

### 🔨 Steps to reproduce
Unknown (was not able to reproduce myself).

**Comment by nicktoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481303556489)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300008636)

**Comment by AndrewVebster** [comment]
Related Bugsnag record - [link](https://app.bugsnag.com/toggldesktop/toggldesktop/errors/5f60602177d0da00189e9ef3?filters[event.since][0][type]=eq&filters[event.since][0][value]=30d&filters[error.status][0][type]=eq&filters[error.status][0][value]=open&filters[event.severity][0][type]=eq&filters[event.severity][0][value]=error)

**Comment by AndrewVebster** [comment]
The fix was released to stable v7.5.279
