### ISSUE TITLE
Autotracker prompt occurs too often

### ISSUE THREAD

**Issue by skel35** [toggl-open-source/toggldesktop#4605]
### 💻 Environment
Platform: Windows (Lib)

### 📒 Description
After #3917 the users of the Autotracker features have started seeing a lot more notifications.
E.g., if the user has set up `Notion` and `Slack` as autotracker terms for 2 different projects, then switching to Slack for a few seconds while doing Notion work always ends up in an autotracker notification, which can be annoying.
Some users have also complained about regular autotracker notifications happening too often.

Proposed solution: show autotracker notification only after a certain window has been in focus for 5+ seconds. The threshold of 5 seconds can be increased in the future depending on user feedback.

**Comment by GitMurf** [comment]
@skel35 for me even a 5 second threshold may not be ideal. My suggestion is that there is a setting/preference a user can switch to say "While a project is running, do not give auto tracker suggestion". That is the way it used to work a few weeks ago and I liked that. I have a timer for example for Google so that if I don't have any timer turned on, when I go to Google it will remind me and ask if I want to start a timer for "Browsing the Web". I like to track time I "waste" just browsing the web with no real task in mind.

But if I am working on Project xyz and have a timer going already, I don't want it to remind me to track/switch to "Browsing the web" when I go to google something that relates to Project xyz. I already have a timer going... I don't want to be suggested a new time entry every time I go to Google or many other similar rules I have setup.

Is this an option/feature on your radar? Thanks!

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481305553837)

**Comment by skel35** [comment]
@dianetoggl please guide the user to the `stable` version. We'll address this before the next `stable` release.

**Comment by skel35** [comment]
@GitMurf @dianetoggl autotracker suggestions while the TE is running are going to be opt-in via a Preferences setting since the next releases

**Comment by GitMurf** [comment]
@skel35 just saw this update! This looks perfect! Thanks.

![image](https://user-images.githubusercontent.com/64155612/98805372-50c01c00-23cc-11eb-98bd-480ab01dd1cf.png)
