### ISSUE TITLE
Editing menu doesn't appear on the right

### ISSUE THREAD

**Issue by devanshbhinde** [toggl-open-source/toggldesktop#4647]
### 💻 Environment

Platform: Windows 10 1903
Toggl Version: 7.5.373

### 🐞 Actual behavior

Editing menu doesn't appear on the right

### 💯 Expected behavior

Clicking on the time entry pops up the menu on the right

### 📦 Additional info

![tempsnip](https://user-images.githubusercontent.com/72598617/98458369-caca8800-21b5-11eb-94ac-bc99cc6914d7.png)

**Comment by skel35** [comment]
Hi @devanshbhinde!
We could not reproduce the issue based on the description.
Could you please provide a screen recording of the issue? Thanks

**Comment by devanshbhinde** [comment]
@skel35 Hey! Sure have a look at this - https://drive.google.com/file/d/1Qag1_tUTI9W-ZuxPN8npeRzpQfG6BgPl/view?usp=sharing

**Comment by skel35** [comment]
Thanks @devanshbhinde, that was helpful!
The Edit view actually does open, but it's outside of the screen. The issue is that our app does not handle well enough the case when the app is resized to the screen width, but not actually maximized.
You can work around it by simply maximizing the app window, or by resizing it to a bit less width so that the Edit view is still visible.
Let me know if that helps.

**Comment by devanshbhinde** [comment]
@skel35 Yes and thank you maximizing fixes it!
