### ISSUE TITLE
Auto tags feature

### ISSUE THREAD

**Issue by dtolstyi** [toggl-open-source/toggldesktop#4816]
### 💻 Environment
Platform: **Windows**

### 📒 Description
For me it would be really useful if we could have periodic time points. E.g. every 40 hours new time point is created.

### ⭐️ Why do you want this?
For a freelancer this can be useful to send invoices when specific amount of hours is spent on project.

### Possible solution
From what I see, it can be easily done using "automatic tags". E.g. you are working on project-X. If "auto-tags" feature is turned on, then tag "project-x-1" is created at the beginning. When specified interval (e.g. 40 hours) has been spent on project, tag automatically changes to "project-x-2" and so on.

What do you think about this feature? Would you accept PR for it if I were to make it?

**Comment by kyllikekimmel** [comment]
Thanks for reaching out to us with this @dtolstyi. We're currently looking into adding the ability to set recurring estimates to Projects in Toggl Track. It sounds like this might help you with what you're looking to achieve as well. Be on the lookout for that later this year. Because of that, we wouldn't add this PR at the moment.

**Comment by dtolstyi** [comment]
Thank you for your reply, @kyllikekimmel! Have a nice day!
