### ISSUE TITLE
Issues due to Required Fields

### ISSUE THREAD

**Issue by kadrihvl** [toggl-open-source/toggldesktop#4868]
### 💻 Environment

Have reproduced the issue on Mac (7.5.441), customer is using latest Win. 
Platform: 
OS Version: 
Toggl Version: 

### 🐞 Actual behavior

If a team is using the Required Fields feature, desktop app is not handling the entries in a user friendly way. Current state:
If a user saves an entry that doesn't have all required fields selected; any following TEs that do have all required elements are not saved either. This can result in extreme data losses. Plus it is not easy for the customer to fix this.
In addition the error message that is displayed - "unmet constraint" - doesn't tell the user what exactly is wrong and how they should act to save their data.

### 💯 Expected behavior

The TE with unmet constrains should be clearly marked and the error should clearly state what the user should do in order to sync this particular TE. All other TEs that are added after the first entry with unmet constrains, should not be affected!! Currently we are not syncing these TEs hence user is running the risk of losing data. Ideally the entry which doesn't meet required fields criteria shouldn't be saved at the first place - like the webapp is currently handling this. 

### 🔨 Steps to reproduce

1. 
2. 
3. 

### 📦 Additional info

Discussion [here](https://toggl.slack.com/archives/C029WCX0T/p1632221260022800)

**Comment by atsvirchkova** [comment]
A buggy workflow related to this bug:

1. Start a TE, that violates some constraints.
2. Stop this TE.
3. Create a TE, that meets all necessary constraints. See the sync error displayed (because of the previous violating TE).
4. Delete the TE, that violates the constraints.

AR: The TE meeting all constraints won't be ever synced.

ER: We need to agree on what we do. Possible solutions:

- Don't allow to stop a TE, which doesn't meet the constraints (like in web). But I think we currently don't store the info about constrains anywhere, so we'd need to think carefully how to implement this.
- Try to sync the TEs, for which sync failed again after the violation is resolved (either with fixing the TE or deleting it).

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309714001)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309715122)
